anime_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('anime_lists.urls')),
]

anime_lists/urls.py
"""urls для аниме листа"""

from django.urls import path
from . import views

app_name = 'anime_lists'
urlpatterns = [
    # home
    path('', views.index, name='index'),
    # title list
    path('titles/', views.titles, name='titles'),
    # information about some title
    path('titles/<int:title_id>/', views.title, name='title'),
]

anime_lists/models.py
import datetime

from django.db import models

# Create your models here.


class Titles(models.Model):
    """Название аниме"""
    text = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Строковое представление модели"""
        return self.text


class Entry(models.Model):
    """Описание аниме"""
    topic = models.ForeignKey(Titles, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return f"{self.text[:30]}..."

anime_lists/views.py
from django.shortcuts import render
from .models import Titles


# Create your views here.

def index(request):
    return render(request, 'anime_lists/index.html')


def titles(request):
    """ getting titles from db """
    all_titles = Titles.objects.order_by('date_added')
    context = {'titles': all_titles}
    return render(request, 'anime_lists/titles.html', context)


def title(request, title_id):
    """ getting info about particular title"""
    title1 = Titles.objects.get(id=title_id)
    entries = title1.entry_set.order_by('-date_added')
    context = {'title': title, 'entries': entries}
    return render(request, 'anime_lists/title.html', context)

anime_lists/templates/anime_lists/base.html
<p>
    <a href="{%  url 'anime_lists:index'%}">Anime List</a> -
    <a href="{% url 'anime_lists:titles'%}">Titles</a>
</p>

{% block content %}

{% endblock content %}

anime_lists/templates/anime_lists/index.html
{% extends "anime_lists/base.html" %}

{% block content %}
<p>Anime List helps you to save information about your favorite anime title.</p>
{% endblock content %}

anime_lists/templates/anime_lists/title.html
{% extends "anime_lists/base.html" %}

{% block content %}

    <p>Title: {{ title }}</p>

    <p>Entries:</p>

        <ul>
          {% for entry in entries %}
              <li>
                <p>{{ entry.date_added|date:'M d, Y H:i'}}</p>
                <p>{{ entry.text | linebreaks }}</p>
              </li>
          {% empty %}
              <li>There are ni entries for this title yet.</li>
          {% endfor %}
        </ul>

{% endblock content %}

anime_lists/templates/anime_lists/titles.html
{% extends "anime_lists/base.html" %}

{% block content %}

    <p>Topics</p>

    <ul>
        {% for title in titles %}
          <li>
            <a href="{% url 'anime_lists:title' title.id %}">{{ title }}</a>
          </li>
        {% empty %}
          <li>No titles have been added yet.</li>
        {% endfor %}
    </ul>
{% endblock content %}